server:
  port: 8080

spring:
  application:
    name: lock-service

mqtt:
  broker: tcp://mosquitto:1883
  clientId: ${HOSTNAME:lock-service}
  username: ${MQTT_USERNAME:}
  password: ${MQTT_PASSWORD:}

  #broker hrani session (subs + QoS1 backlog) med disconnectom
  cleanSession: false
  qos: 1

#logiranje
logging:
  level:
    io.github.safeslope.mqtt: DEBUG
    org.eclipse.paho.client.mqttv3: INFO

services:
  ski-card-verification:
    base-url: ${SKI_CARD_VERIFICATION_BASE_URL:http://ski-card-verification:8080}
    resort-id: ${RESORT_ID:1}
  anti-abuse:
    base-url: ${ANTI_ABUSE_BASE_URL:http://anti-abuse:8080}